# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFailureToLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_failureToLogin(self):
    self.driver.get("https://www.qa.com/")
    self.driver.set_window_size(1296, 1400)

    assert self.driver.title == "QA | World-Leading Tech Training, Skills, Talent & Apprenticeships"

    self.driver.find_element(By.NAME, "search").send_keys("az900")
    self.driver.find_element(By.LINK_TEXT, "Microsoft Azure Fundamentals (Technical) Total Learning (AZ-900)(MAZ9000-TL)").click()

    assert self.driver.title == "Microsoft Azure Fundamentals (Technical) Total Learning (AZ-900) (MAZ9000-TL)"

    self.driver.find_element(By.LINK_TEXT, "Sign In").click()

    assert self.driver.title == "Sign In with Auth0"

    self.driver.find_element(By.ID, "email").send_keys("amccall@qa.com")
    self.driver.find_element(By.ID, "btn-login").click()

    assert self.driver.find_element(By.CSS_SELECTOR, ".input-error").text == "Invalid, check your credentials and try again"
  
testCase = TestFailureToLogin()
testCase.setup_method()
testCase.test_failureToLogin()
testCase.teardown_method()